config/routes.rb
Rails.application.routes.draw do

  resources :emails, only: :index, format: :js

  root to: "pages#index"
  get "share" => "pages#share"

  devise_for :users, only: [:registrations, :sessions, :confirmations, :unlocks, :passwords]

  resources :subscriptions, only: [:new, :create] do
    get :pending, on: :collection
  end

  get "subscriptions/:confirmation_token/confirm" => "subscriptions#confirm", as: :confirm_subscription

  namespace :api do
    namespace :v1 do
      resources :access_tokens, path: :token, only: :create, format: false
    end
  end

end

app/models/access_token.rb
class AccessToken < ActiveRecord::Base
  include HardenedToken
  hardened_token

  belongs_to :user

end

app/models/concerns/hardened_token.rb
module HardenedToken
  extend ActiveSupport::Concern

  LOCATOR_LENGTH = { bytes: 48.freeze, chars: 64.freeze }.freeze
  SECRET_LENGTH = { bytes: 192.freeze, chars: 256.freeze }.freeze

  def unencrypted
    "#{locator}:#{secret}"
  end

  class_methods do

    def hardened_token
      attr_encrypted :secret, random_iv: true

      before_validation do
        self.locator = self.class.generate_locator if locator.blank?
        self.secret = self.class.generate_secret if secret.blank?
      end

      validates_length_of :locator, is: LOCATOR_LENGTH[:chars]
      validates_uniqueness_of :locator, case_sensitive: true

      validates_length_of :secret, is: SECRET_LENGTH[:chars]
      validates :encrypted_secret, symmetric_encryption: true
    end

    def generate_locator
      SecureRandom.urlsafe_base64 LOCATOR_LENGTH[:bytes]
    end

    def generate_secret
      SecureRandom.urlsafe_base64 SECRET_LENGTH[:bytes]
    end
  end

end

app/models/invite.rb
class Invite < ActiveRecord::Base

  def self.send_invite(email)
    transaction do
      invite = create!(email: email, token: SecureRandom.hex)
      InviteMailer.invite(invite).deliver_now!
    end
  end

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base

  validates :email, uniqueness: true, presence: true
  validates :confirmation_token, uniqueness: true, presence: true
  validates_presence_of :start_on

  scope :confirmation_overdue, -> { where("created_at < ?", 3.days.ago).where(confirmed: false) }

  after_initialize :init_start_on

  def self.create_and_request_confirmation(params)
    transaction do
      subscription = create!(
        email: params[:email],
        start_on: params[:start_on],
        confirmation_token: generate_confirmation_token
      )
      SubscriptionMailer.send_confirmation_request!(subscription)
      subscription
    end
  end

  def self.generate_confirmation_token
    SecureRandom.hex(32)
  end

  def self.confirm(confirmation_token)
    subscription = find_by!(confirmation_token: confirmation_token)
    subscription.update!(confirmed: true)
    subscription
  end

  def to_param
    confirmation_token
  end

  private

  def init_start_on
    self.start_on = Time.zone.today if new_record? && start_on.blank?
  end

end

app/models/token_guardian.rb
class TokenGuardian

  attr_reader :encryptor, :params

  def self.build(controller:)
    # Borrow MessageEncryptor, thank you CookieJar.
    encryptor = controller.request.cookie_jar.encrypted.instance_variable_get :@encryptor
    TokenGuardian.new(encryptor: encryptor, params: controller.params)
  end

  def initialize(encryptor:, params:)
    @encryptor = encryptor
    @params = params
  end

  def issue_token
    user = authenticate_user
    access_token = user.issue_access_token
    encryptor.encrypt_and_sign(access_token.unencrypted)
  end

  private

  def authenticate_user
    authenticate_user_with_devise
  end

  def authenticate_user_with_devise
    user = User.find_for_database_authentication(email: user_params[:email])

    if user && user.valid_for_authentication? { user.valid_password?(user_params[:password]) }
      user.update_attribute(:failed_attempts, 0) unless user.failed_attempts.zero?
      return user
    end

    raise UnauthorizedAccess
  end

  def user_params
    @user_params ||= if @user_params.nil?
      user_parameters = params.require(:user)
      user_parameters.require(:email)
      user_parameters.require(:password)
      user_parameters.permit(:email, :password)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  has_many :access_tokens, dependent: :destroy

  def self.emails_starting_with(email)
    where("email LIKE ?", "#{email}%").order(email: :asc).limit(20).pluck(:email)
  end

  def issue_access_token
    access_tokens.create!
  end
end

app/controllers/api/api_controller.rb
class Api::ApiController < ActionController::Base
  protect_from_forgery with: :null_session

  def self.disable_turbolinks_cookies
    skip_before_action :set_request_method_cookie
  end

  disable_turbolinks_cookies
end

app/controllers/api/v1/access_tokens_controller.rb
class Api::V1::AccessTokensController < Api::ApiController

  def create
    respond_to_json do
      render json: { access_token: token_guardian.issue_token }, status: :created
    end
  end

  private

  def respond_to_json
    assert_request_content_type Mime::JSON
    respond_to { |format| format.json { yield } }
  end

  def assert_request_content_type(content_type)
    raise UnsupportedMediaType unless request.content_type == content_type
  end
  
  def token_guardian
    @token_guardian ||= TokenGuardian.build(controller: self)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController

  def index
    # Then explore how this could be cached with Rails.cache (or automatic query cache?)
    # Mention privacy concerns, would be less of a concern with public usernames
    # (like GitHub usernames are widely accepted as being public)
    email = params.fetch(:email, '')
    @emails = email.size < 2 ? [] : User.emails_starting_with(email)
  end

end

app/controllers/invited_users_controller.rb
class InvitedUsersController < ApplicationController
  def new
    @invite = Invite.find_by(token: params[:token])
  end

  def create
    invite = Invite.find_by(invite_params)
    user = User.new(user_params)
    user.email = invite.email
    if user.save
      flash[:notice] = "A message with a confirmation link has been sent to your
        email address. Please follow the link to activate your account."
    else
      flash[:alert] = "Sorry, there was a problem registering the invited user."
    end
    redirect_to root_path
  end

  private

  def invite_params
    params.require(:invite).permit(:token)
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  def new
    @subscription = Subscription.new
  end

  def create
    Subscription.create_and_request_confirmation(subscription_params)
    redirect_to pending_subscriptions_path
  end

  def pending
  end

  def confirm
    confirmation_token = params.require(:confirmation_token).to_s
    @subscription = Subscription.confirm(confirmation_token)
  end

  private

  def subscription_params
    params.require(:subscription).permit(:email, :start_on)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  attr_writer :page_title

  def page_title
    @page_title ||= "RSpec Rails Examples"
  end
  
end

app/views/invited_users/new.html.erb
<h1>Register</h1>

<%= form_for(:user, url: invited_users_path) do |user_form| %>
  <%= fields_for @invite do |invite_fields| %>
    <%= invite_fields.hidden_field :token %>
  <% end %>

  <%= user_form.label :password, "Choose a password" %>
  <%= user_form.password_field :password, autocomplete: "off" %>
  <br>

  <%= user_form.label :password_confirmation, "Re-enter your chosen password" %>
  <%= user_form.password_field :password_confirmation, autocomplete: "off" %>
  <br>

  <%= user_form.submit "Register" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= notice %>
<%= alert %>

<%= yield %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/pages/index.html.erb
<% self.page_title = "Welcome to RSpec Rails Examples" %>
<h1><%= page_title %></h1>
<% if user_signed_in? %>
  <p>Hello, <%= current_user.email %></p>
  <nav><%= button_to "Log out", destroy_user_session_path, method: :delete %></nav>
<% else %>
  <p>Not registered? <%= link_to "Sign up", new_user_registration_path %></p>
  <nav>
    <%= link_to "Log in", new_user_session_path %>
    <%= link_to "Subscribe to newsletter", new_subscription_path %>
  </nav>
<% end %>


<%= form_tag do %>
  <%= label_tag :email %>
  <%= text_field_tag :email, '',
        inputmode: :email,
        list: :emails,
        'data-remote': true,
        'data-method': :get,
        'data-url': '/emails',
        'oninput': 'jQuery(this).change();'
  %>
  <datalist id="emails">
  </datalist>
<% end %>

app/views/pages/share.html.erb
<% self.page_title = "Share Our Stuff!" %>
<h1><%= page_title %></h1>

<!-- 3rd party script appends "Share this" button to page -->
<script class="social-widget" src="https://eliotsykes.github.io/rspec-rails-examples/share.js"></script>

app/views/subscriptions/confirm.html.erb
<% self.page_title = "Subscription confirmed!" %>
<p>
  Your subscription will start on <%= @subscription.start_on.to_formatted_s(:long_ordinal) %>, thank you!
</p>

app/views/subscriptions/new.html.erb
<% self.page_title = "Subscribe to our newsletter" %>
<%= form_for @subscription do |f| %>
  <%= f.label :email, "Email" %>
  <%= f.email_field :email %>

  <%= f.label :start_on, "Start date" %>
  <%= f.date_field :start_on %>

  <%= f.submit "Subscribe" %>
<% end %>

app/views/subscriptions/pending.html.erb
<% self.page_title = "Check your inbox" %>
<p>
  Please check your inbox and click the confirmation link to complete your subscription.
</p>